import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.160.0/build/three.module.js';
import {FontLoader} from 'https://cdn.jsdelivr.net/npm/three@0.160.0/examples/jsm/loaders/FontLoader.js';
import {TextGeometry} from 'https://cdn.jsdelivr.net/npm/three@0.160.0/examples/jsm/geometries/TextGeometry.js';
import {EffectComposer} from 'https://cdn.jsdelivr.net/npm/three@0.160.0/examples/jsm/postprocessing/EffectComposer.js';
import {RenderPass} from 'https://cdn.jsdelivr.net/npm/three@0.160.0/examples/jsm/postprocessing/RenderPass.js';
import {UnrealBloomPass} from 'https://cdn.jsdelivr.net/npm/three@0.160.0/examples/jsm/postprocessing/UnrealBloomPass.js';

const root=document.documentElement;
const stage=document.getElementById('stage');
const statusNode=document.getElementById('status');
const realityButton=document.getElementById('realityToggle');
const audioButton=document.getElementById('audioToggle');
const cursor=document.getElementById('cursor');
const kissCanvas=document.getElementById('kissCanvas');
const coarse=window.matchMedia('(pointer: coarse)');
const reduced=window.matchMedia('(prefers-reduced-motion: reduce)');
let renderer=null,scene=null,camera=null,composer=null,bloom=null,fluid=null,foilGroup=null,asteroid=null,artifacts=null;
let viewportWidth=1,viewportHeight=1,baseDpr=Math.min(window.devicePixelRatio||1,2),targetDpr=baseDpr;
let lastFrame=performance.now(),frameHandle=0,badFrames=0,slowFrames=0,frameCounter=0,fps=60;
let pointer=new THREE.Vector2(),pointerGoal=new THREE.Vector2(),pointerVelocity=new THREE.Vector2(),lastPointer=new THREE.Vector2();
let scrollVelocity=0,lastScroll=window.scrollY;
let virtualReality=true,audioContext=null,analyser=null,audioData=null;
const disposables=[];

function setViewport(){const height=window.visualViewport?window.visualViewport.height:window.innerHeight;root.style.setProperty('--vh',`${height}px`);}
setViewport();
window.visualViewport?.addEventListener('resize',setViewport,{passive:true});
const resizeObserver=new ResizeObserver(entries=>{for(const entry of entries){viewportWidth=Math.max(1,entry.contentRect.width);viewportHeight=Math.max(1,entry.contentRect.height);resize();}});
resizeObserver.observe(stage);

const fluidVertex=`varying vec2 vUv;void main(){vUv=uv;gl_Position=vec4(position,1.0);}`;
const fluidFragment=`precision highp float;varying vec2 vUv;uniform float uTime;uniform vec2 uPointer;uniform vec2 uVelocity;uniform float uAudio;uniform float uReality;float hash21(vec2 p){p=fract(p*vec2(127.1,311.7));p+=dot(p,p+41.7);return fract(p.x*p.y);}float noise(vec2 p){vec2 i=floor(p),f=fract(p);f=f*f*(3.0-2.0*f);return mix(mix(hash21(i),hash21(i+vec2(1.0,0.0)),f.x),mix(hash21(i+vec2(0.0,1.0)),hash21(i+vec2(1.0,1.0)),f.x),f.y);}float fbm(vec2 p){float value=0.0;float amp=.5;for(int i=0;i<5;i++){value+=amp*noise(p);p*=2.0;amp*=.5;}return value;}void main(){vec2 p=vUv*2.0-1.0;p.x*=1.6;vec2 q=p-uPointer*.2;float field=fbm(q*2.2+uTime*.025);float metab=sin(length(q)*7.0-field*5.0-uTime*.08+dot(uVelocity,q)*2.0+uAudio*4.0);float mask=smoothstep(.72,.98,metab*.5+.5);float edge=smoothstep(1.45,.05,length(p));float blue=uReality*.012;vec3 c=vec3(mask*.035+blue*.1,mask*.025,mask*.04+blue);gl_FragColor=vec4(c*edge,1.0);}`;
const mossVertex=`varying vec3 vNormal;varying vec3 vWorld;uniform float uTime;uniform float uAudio;float wave(vec3 p){return sin(p.x*4.1+uTime*.35)+sin(p.y*3.7-uTime*.22)+sin(p.z*5.0+uTime*.18);}void main(){vec3 p=position+normal*(wave(normalize(position)*2.7)*.045+uAudio*.035);vNormal=normal;vec4 world=modelMatrix*vec4(p,1.0);vWorld=world.xyz;gl_Position=projectionMatrix*viewMatrix*world;}`;
const mossFragment=`precision highp float;varying vec3 vNormal;varying vec3 vWorld;uniform float uTime;void main(){vec3 light=normalize(vec3(2.0,4.0,5.0));float diffuse=max(dot(normalize(vNormal),light),0.0);float fibers=.5+.5*sin(vWorld.x*18.0+vWorld.y*15.0+vWorld.z*13.0+uTime*1.5);vec3 moss=mix(vec3(.01,.04,.008),vec3(.12,.34,.045),fibers);float scatter=pow(1.0-diffuse,2.2)*.16;gl_FragColor=vec4(moss*(.28+diffuse)+scatter,1.0);}`;

function initRenderer(){if(reduced.matches)return false;try{renderer=new THREE.WebGLRenderer({antialias:false,alpha:false,powerPreference:'high-performance',stencil:false});renderer.setClearColor(0x000000,1);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;stage.replaceChildren(renderer.domElement);disposables.push(renderer);return true;}catch(error){statusNode.textContent='[ DOM_FALLBACK :: READY ]';return false;}}
function foilMaterial(){return new THREE.MeshPhysicalMaterial({color:0xf7f7f7,metalness:.9,roughness:.08,clearcoat:1,clearcoatRoughness:.03,iridescence:1,iridescenceIOR:1.45,iridescenceThicknessRange:[120,600]});}
function createFoil(){foilGroup=new THREE.Group();foilGroup.position.set(0,.4,0);scene.add(foilGroup);const loader=new FontLoader();loader.load('https://cdn.jsdelivr.net/npm/three@0.160.0/examples/fonts/helvetiker_bold.typeface.json',font=>{const letters=[['M',-3.2],['I',-1.05],['S',.55],['H',2.85]];for(const [char,x] of letters){const geometry=new TextGeometry(char,{font,size:2.05,height:.45,curveSegments:7,bevelEnabled:true,bevelThickness:.15,bevelSize:.08,bevelSegments:12});geometry.center();const mesh=new THREE.Mesh(geometry,foilMaterial());mesh.position.x=x;foilGroup.add(mesh);disposables.push(geometry,mesh.material);}});}
function createAsteroid(){const geometry=new THREE.IcosahedronGeometry(2.3,5);const material=new THREE.ShaderMaterial({uniforms:{uTime:{value:0},uAudio:{value:0}},vertexShader:mossVertex,fragmentShader:mossFragment});asteroid=new THREE.Mesh(geometry,material);asteroid.position.set(4,-1.2,-1);scene.add(asteroid);disposables.push(geometry,material);}
function createArtifacts(){artifacts=new THREE.Group();scene.add(artifacts);const heart=new THREE.Mesh(new THREE.TorusKnotGeometry(.8,.2,64,12,2,3),foilMaterial());heart.position.set(-4,-2,0);const ring=new THREE.Mesh(new THREE.TorusGeometry(1.35,.07,18,96),foilMaterial());ring.position.set(3,2,-1);ring.rotation.x=1.2;const balloon=new THREE.Mesh(new THREE.SphereGeometry(.8,32,20),foilMaterial());balloon.position.set(-3,2,-1);balloon.scale.set(1.2,.7,1.2);artifacts.add(heart,ring,balloon);for(const item of artifacts.children)disposables.push(item.geometry,item.material);}
function createScene(){scene=new THREE.Scene();camera=new THREE.PerspectiveCamera(42,1,.1,100);camera.position.z=12;scene.add(new THREE.AmbientLight(0xffffff,.55));const key=new THREE.DirectionalLight(0xffffff,2.2);key.position.set(4,6,8);scene.add(key);const rim=new THREE.PointLight(0x5533ff,18,30);rim.position.set(-5,2,4);scene.add(rim);const geometry=new THREE.PlaneGeometry(2,2);const material=new THREE.ShaderMaterial({vertexShader:fluidVertex,fragmentShader:fluidFragment,uniforms:{uTime:{value:0},uPointer:{value:new THREE.Vector2()},uVelocity:{value:new THREE.Vector2()},uAudio:{value:0},uReality:{value:1}},depthWrite:false,depthTest:false});fluid=new THREE.Mesh(geometry,material);fluid.frustumCulled=false;scene.add(fluid);disposables.push(geometry,material);createFoil();createAsteroid();createArtifacts();composer=new EffectComposer(renderer);composer.addPass(new RenderPass(scene,camera));bloom=new UnrealBloomPass(new THREE.Vector2(1,1),.4,.65,.85);composer.addPass(bloom);}
function resize(){if(!renderer||!camera)return;renderer.setPixelRatio(targetDpr);renderer.setSize(viewportWidth,viewportHeight,false);camera.aspect=viewportWidth/viewportHeight;camera.updateProjectionMatrix();composer?.setSize(viewportWidth,viewportHeight);}
function readAudio(){if(!analyser||!audioData)return 0;analyser.getByteFrequencyData(audioData);let total=0;for(let i=0;i<audioData.length;i++)total+=audioData[i];return total/audioData.length/255;}
function quality(delta){if(delta>.0166)badFrames++;else badFrames=Math.max(0,badFrames-2);if(delta>.0333)slowFrames++;else slowFrames=Math.max(0,slowFrames-1);if(badFrames>=30){targetDpr=Math.max(1,targetDpr-.25);badFrames=0;resize();}if(slowFrames>=10&&bloom)bloom.enabled=false;if(delta<.024&&badFrames===0&&targetDpr<baseDpr){targetDpr=Math.min(baseDpr,targetDpr+.05);resize();}frameCounter++;if(frameCounter%15===0){fps=Math.round(1/Math.max(delta,.001));statusNode.textContent=`[ ${virtualReality?'VIRTUAL_ROBLOX':'INFINITE_COSMOS'} :: TIER_${targetDpr<1.5?'MOBILE':'CINEMATIC'} :: ${fps}FPS ]`;}}
function animate(now){const delta=Math.min(.1,(now-lastFrame)/1000);lastFrame=now;if(delta>.0333&&frameCounter%2){frameHandle=requestAnimationFrame(animate);return;}quality(delta);pointer.lerp(pointerGoal,.1);const audio=readAudio();const t=performance.now()*.001;if(fluid){fluid.material.uniforms.uTime.value=t;fluid.material.uniforms.uPointer.value.copy(pointer);fluid.material.uniforms.uVelocity.value.copy(pointerVelocity);fluid.material.uniforms.uAudio.value=audio;fluid.material.uniforms.uReality.value=virtualReality?1:0;}if(foilGroup){foilGroup.rotation.y+=(pointer.x*.18-foilGroup.rotation.y)*.035;foilGroup.rotation.x+=(pointer.y*.1-foilGroup.rotation.x)*.03;}if(asteroid){asteroid.rotation.x+=.0015;asteroid.rotation.y+=.002;asteroid.material.uniforms.uTime.value=t;asteroid.material.uniforms.uAudio.value=audio;}if(artifacts){artifacts.rotation.y+=.0015;artifacts.children.forEach((item,index)=>item.position.y+=Math.sin(t*.7+index)*.0005);}if(composer&&bloom?.enabled)composer.render(delta);else renderer.render(scene,camera);frameHandle=requestAnimationFrame(animate);}

function initAudio(){if(audioContext)return;try{audioContext=new AudioContext();analyser=audioContext.createAnalyser();analyser.fftSize=128;audioData=new Uint8Array(analyser.frequencyBinCount);const master=audioContext.createGain();master.gain.value=.035;master.connect(analyser);analyser.connect(audioContext.destination);[130.81,164.81,196,261.63,329.63].forEach((frequency,index)=>{const osc=audioContext.createOscillator();const gain=audioContext.createGain();const filter=audioContext.createBiquadFilter();osc.type=index%2?'triangle':'sine';osc.frequency.value=frequency;filter.type='lowpass';filter.frequency.value=850;gain.gain.value=.12/(index+1);osc.connect(filter);filter.connect(gain);gain.connect(master);osc.start();});audioButton.textContent='[ AMBIENT_AUDIO :: ON ]';}catch(error){audioButton.textContent='[ AUDIO :: UNAVAILABLE ]';}}
function kiss(){const context=kissCanvas.getContext('2d');const scale=devicePixelRatio||1;kissCanvas.width=innerWidth*scale;kissCanvas.height=innerHeight*scale;context.setTransform(scale,0,0,scale,0,0);const particles=Array.from({length:500},()=>({x:innerWidth*.5+(Math.random()-.5)*80,y:innerHeight*.68,vx:(Math.random()-.5)*11,vy:-Math.random()*15-3,r:Math.random()*2+1,life:1}));let previous=performance.now();function step(now){const dt=Math.min(.033,(now-previous)/1000);previous=now;context.clearRect(0,0,innerWidth,innerHeight);let alive=0;for(const p of particles){p.vy+=22*dt;p.x+=p.vx*60*dt;p.y+=p.vy*60*dt;p.life-=dt*.38;if(p.y>innerHeight-20){p.y=innerHeight-20;p.vy*=-.62;}if(p.life>0){alive++;context.globalAlpha=p.life;context.fillStyle='rgba(255,190,225,.9)';context.beginPath();context.arc(p.x,p.y,p.r,0,Math.PI*2);context.fill();}}context.globalAlpha=1;if(alive)requestAnimationFrame(step);}requestAnimationFrame(step);}
const letter='Mish,\n\nIf this little universe ever feels impossibly large, remember that it was built from small moments: a message, a laugh, a game, a plan, a memory worth keeping.\n\nI wanted a place where those moments could stay alive and where every future memory still has somewhere to land.\n\nAlways becoming,\nIsira';
function decrypt(){const modal=document.getElementById('letterModal'),output=document.getElementById('letterText');modal.hidden=false;const alphabet='ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789ΔΩΣЖλπ01';let index=0;const timer=setInterval(()=>{output.textContent=letter.split('').map((char,i)=>i<index?char:char==='\n'?'\n':alphabet[Math.floor(Math.random()*alphabet.length)]).join('');index++;if(index>letter.length){clearInterval(timer);output.textContent=letter;}},22);}
function closeLetter(){document.getElementById('letterModal').hidden=true;}
function toggleReality(){virtualReality=!virtualReality;realityButton.textContent=virtualReality?'[ REALITY :: VIRTUAL_ROBLOX ]':'[ REALITY :: INFINITE_COSMOS ]';if(bloom)bloom.strength=virtualReality?.4:.65;}
function updateClock(){const diff=Math.max(0,Date.now()-Date.parse('2023-01-01T00:00:00Z'));const seconds=Math.floor(diff/1000);document.getElementById('days').textContent=Math.floor(seconds/86400).toLocaleString();document.getElementById('hours').textContent=String(Math.floor(seconds/3600)%24).padStart(2,'0');document.getElementById('minutes').textContent=String(Math.floor(seconds/60)%60).padStart(2,'0');document.getElementById('seconds').textContent=String(seconds%60).padStart(2,'0');}
function dispose(){cancelAnimationFrame(frameHandle);resizeObserver.disconnect();if(scene)scene.traverse(object=>{object.geometry?.dispose();if(Array.isArray(object.material))object.material.forEach(item=>item.dispose());else object.material?.dispose();});composer?.dispose();renderer?.dispose();renderer?.forceContextLoss?.();}
window.addEventListener('scroll',()=>{const current=window.scrollY;scrollVelocity=(current-lastScroll)*.08;lastScroll=current;},{passive:true});
window.addEventListener('pointermove',event=>{const x=event.clientX/innerWidth*2-1,y=-(event.clientY/innerHeight*2-1);pointerVelocity.set(x-lastPointer.x,y-lastPointer.y);lastPointer.set(x,y);pointerGoal.set(x,y);if(!coarse.matches){cursor.style.left=`${event.clientX}px`;cursor.style.top=`${event.clientY}px`;cursor.classList.toggle('big',Boolean(event.target.closest('a,button,.memory')));}}, {passive:true});
window.addEventListener('touchmove',event=>{const touch=event.touches[0];if(touch){const x=touch.clientX/innerWidth*2-1,y=-(touch.clientY/innerHeight*2-1);pointerVelocity.set(x-lastPointer.x,y-lastPointer.y);lastPointer.set(x,y);pointerGoal.set(x,y);}}, {passive:true});
window.addEventListener('pointerdown',initAudio,{passive:true});
window.addEventListener('touchstart',initAudio,{passive:true});
audioButton.addEventListener('click',()=>{initAudio();audioContext?.resume();});
realityButton.addEventListener('click',toggleReality);document.getElementById('kiss').addEventListener('click',kiss);document.getElementById('openLetter').addEventListener('click',decrypt);document.getElementById('closeLetter').addEventListener('click',closeLetter);
const memoryObserver=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting)entry.target.classList.add('is-active');else if(!coarse.matches)entry.target.classList.remove('is-active');}),{threshold:.55});document.querySelectorAll('.memory').forEach(memory=>{memoryObserver.observe(memory);memory.querySelector('img').addEventListener('error',event=>{const fallback=event.currentTarget.dataset.fallback;if(fallback&&event.currentTarget.src!==new URL(fallback,location.href).href)event.currentTarget.src=fallback;});});
setInterval(updateClock,1000);updateClock();
window.addEventListener('pagehide',dispose,{once:true});

if(initRenderer()){createScene();resize();frameHandle=requestAnimationFrame(animate);}